apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-data
              mountPath: /prometheus
            - name: prometheus-tls
              mountPath: /etc/prometheus/secrets
              readOnly: true # Zertifikate sind nur lesbar
            - name: prometheus-ca # Hinzufügen des CA-Zertifikats-Volumes
              mountPath: /etc/prometheus/secrets
              readOnly: true # Das CA-Zertifikat ist nur lesbar
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-data
          emptyDir: {}
        - name: prometheus-tls
          secret:
            secretName: prometheus-tls
        - name: prometheus-ca
          secret:
            secretName: prometheus-ca # Das Secret für das CA-Zertifikat
