apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: prometheus # Namespace für Prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-data
              mountPath: /prometheus
            - name: prometheus-tls
              mountPath: /etc/prometheus/tls # TLS-Zertifikate in ein eigenes Verzeichnis
              readOnly: true # Zertifikate sind nur lesbar
            - name: prometheus-ca
              mountPath: /etc/prometheus/ca # CA-Zertifikat in ein eigenes Verzeichnis
              readOnly: true # CA-Zertifikat ist nur lesbar
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config # Die ConfigMap bleibt erhalten
        - name: prometheus-data
          emptyDir: {}
        - name: prometheus-tls
          secret:
            secretName: prometheus-tls # Das Secret für TLS-Zertifikate
        - name: prometheus-ca
          secret:
            secretName: prometheus-ca # Das Secret für das CA-Zertifikat
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: prometheus # Namespace für Prometheus
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus
  type: NodePort # NodePort für externen Zugriff
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes'
        kubernetes_sd_configs:
          - role: node
        scheme: https               # HTTPS aktivieren
        metrics_path: /metrics      # Oder /metrics/cadvisor, je nach dem Endpoint
        tls_config:
          ca_file: /etc/prometheus/ca/ca.crt    # CA-Zertifikat
          cert_file: /etc/prometheus/tls/tls.crt  # Server-Zertifikat
          key_file: /etc/prometheus/tls/tls.key   # Der private Schlüssel
        relabel_configs:
          - source_labels: [__meta_kubernetes_node_name]
            target_label: instance
