apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-monitor
  namespace: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  endpoints:
    - port: prometheus
      interval: 30s
