apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-monitor
  namespace: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus
spec:
  endpoints:
    - interval: 30s
      port: prometheus # Stelle sicher, dass der Portname mit dem Service übereinstimmt
  selector:
    matchLabels:
      app: prometheus # Der Selector muss mit dem Label des Prometheus-Service übereinstimmen
